version: "3.8"
services:
  backend:
    build:
      context: ./GameCenter-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/game_shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: group7
    depends_on:
      - db

  frontend:
    build:
      context: ./GameCenter-Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: group7
      POSTGRES_DB: game_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: